# Generated by Django 4.2.3 on 2023-09-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Jobt',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Users',
        ),
    ]
