# Generated by Django 3.1.14 on 2026-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20260215_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
