# Generated by Django 4.2.6 on 2023-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='olt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('ip_addr', models.GenericIPAddressField()),
            ],
        ),
    ]
