# Generated by Django 5.1.7 on 2025-04-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_list', to='snmp.node')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('snmp_community_ro', models.CharField(default='public', max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('ats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='snmp.ats')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.CharField(blank=True, max_length=64, null=True)),
                ('admin_state', models.CharField(blank=True, max_length=64, null=True)),
                ('oper_state', models.CharField(blank=True, max_length=64, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='snmp.switch')),
            ],
            options={
                'unique_together': {('switch', 'port_index')},
            },
        ),
    ]
