# Generated by Django 4.2.6 on 2024-02-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subnet', models.GenericIPAddressField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=200)),
                ('rx_oid', models.CharField(blank=True, max_length=200, null=True)),
                ('tx_oid', models.CharField(blank=True, max_length=200, null=True)),
                ('part_num_oid', models.CharField(blank=True, max_length=200, null=True)),
                ('sfp_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.CharField(blank=True, max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('snmp_community', models.CharField(default='snmp2netread', max_length=100)),
                ('sysdescr_oid', models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('rx_signal', models.FloatField(blank=True, null=True)),
                ('tx_signal', models.FloatField(blank=True, null=True)),
                ('sfp_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('high_signal_value', models.FloatField(blank=True, default='11', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.branch')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.switchmodel')),
                ('uplink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.switch')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSwitch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uptime', models.CharField(blank=True, max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('snmp_community', models.CharField(default='snmp2netread', max_length=100)),
                ('sysdescr_oid', models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('rx_signal', models.FloatField(blank=True, null=True)),
                ('tx_signal', models.FloatField(blank=True, null=True)),
                ('sfp_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('high_signal_value', models.FloatField(blank=True, default='11', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.switchmodel')),
                ('uplink', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.switch')),
            ],
            options={
                'verbose_name': 'historical switch',
                'verbose_name_plural': 'historical switchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
