# Generated by Django 4.2.6 on 2024-02-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMacHistory',
            fields=[
                ('mac', models.CharField(default='', max_length=17)),
                ('port', models.SmallIntegerField()),
                ('vlan', models.SmallIntegerField()),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mat_listmachistory',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='part_number',
            new_name='part_number_uplink',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='sfp_vendor',
            new_name='physical',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='rx_signal',
            new_name='rx_signal_uplink',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='tx_signal',
            new_name='tx_signal_uplink',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='part_number',
            new_name='part_number_uplink',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='sfp_vendor',
            new_name='physical',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='rx_signal',
            new_name='rx_signal_uplink',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='tx_signal',
            new_name='tx_signal_uplink',
        ),
        migrations.RemoveField(
            model_name='historicalswitch',
            name='snmp_community',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='snmp_community',
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='mac',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='sfp_vendor_uplink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='snmp_community_ro',
            field=models.CharField(default='snmp2netread', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='snmp_community_rw',
            field=models.CharField(default='netman', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='soft_version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='vendor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='sfp_vendor_uplink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_community_ro',
            field=models.CharField(default='snmp2netread', max_length=20),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_community_rw',
            field=models.CharField(default='netman', max_length=20),
        ),
        migrations.AddField(
            model_name='switch',
            name='soft_version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='vendor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SwitchesNeighbors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac1', models.CharField(max_length=17)),
                ('port1', models.SmallIntegerField()),
                ('mac2', models.CharField(max_length=17)),
                ('port2', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'switches_neighbors',
                'managed': True,
                'unique_together': {('mac1', 'port1', 'mac2')},
            },
        ),
        migrations.CreateModel(
            name='SwitchesPorts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.SmallIntegerField()),
                ('speed', models.IntegerField()),
                ('duplex', models.SmallIntegerField()),
                ('admin', models.SmallIntegerField()),
                ('oper', models.SmallIntegerField()),
                ('lastchange', models.BigIntegerField()),
                ('discards_in', models.BigIntegerField()),
                ('discards_out', models.BigIntegerField()),
                ('stp_admin', models.SmallIntegerField()),
                ('stp_state', models.SmallIntegerField()),
                ('poe_admin', models.SmallIntegerField()),
                ('poe_detection', models.SmallIntegerField()),
                ('poe_class', models.SmallIntegerField()),
                ('poe_mpower', models.SmallIntegerField()),
                ('mac_count', models.SmallIntegerField()),
                ('pvid', models.SmallIntegerField()),
                ('port_tagged', models.CharField(max_length=2000)),
                ('port_untagged', models.CharField(max_length=80)),
                ('data', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=80)),
                ('oct_in', models.BigIntegerField()),
                ('oct_out', models.BigIntegerField()),
                ('switch', models.ForeignKey(db_column='switch', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ports', to='snmp.switch')),
            ],
            options={
                'db_table': 'switches_ports',
                'managed': True,
                'unique_together': {('switch', 'port')},
            },
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(default='', max_length=17)),
                ('port', models.SmallIntegerField()),
                ('vlan', models.SmallIntegerField()),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(db_column='switch', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mac_switch', to='snmp.switch')),
            ],
            options={
                'db_table': 'mac',
                'managed': True,
                'unique_together': {('switch', 'mac', 'vlan')},
            },
        ),
    ]
