# Generated by Django 5.1.7 on 2025-04-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchPortStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('octets_in', models.BigIntegerField()),
                ('octets_out', models.BigIntegerField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='snmp.switchport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
