# Generated by Django 4.2.6 on 2023-11-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSwitch',
        ),
    ]
