# Generated by Django 4.2.6 on 2024-02-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0002_listmachistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='last_update',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
