# Generated by Django 4.2.6 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0002_vendor_olt_sysinfo_olt_uptime_switch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='snmp_community',
            field=models.CharField(default='public', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_community',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
