# Generated by Django 4.2.11 on 2025-04-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0002_switchportstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='switchport',
            unique_together=set(),
        ),
    ]
