# Generated by Django 4.2.6 on 2023-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_auto_20231106_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olt',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='switch',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
