# Generated by Django 4.2.6 on 2023-10-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_olt_snmp_community_switch_snmp_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olt',
            name='model',
        ),
        migrations.RemoveField(
            model_name='olt',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='model',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='vendor',
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceModel', models.CharField(max_length=200)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='olt',
            name='deviceModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.devicemodel'),
        ),
        migrations.AddField(
            model_name='switch',
            name='deviceModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.devicemodel'),
        ),
    ]
