# Generated by Django 4.2.6 on 2023-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_olt_device_ip_switch_device_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olt',
            name='device_sn',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_sn',
        ),
        migrations.AddField(
            model_name='olt',
            name='device_general_oid',
            field=models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200),
        ),
        migrations.AddField(
            model_name='olt',
            name='device_optical_info',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='device_snmp_community',
            field=models.CharField(default='snmp2netread', max_length=100),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_general_oid',
            field=models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_optical_info',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_snmp_community',
            field=models.CharField(default='snmp2netread', max_length=100),
        ),
    ]
