# Generated by Django 4.2.6 on 2023-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_delete_historicalswitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='uptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
