# Generated by Django 4.2.11 on 2025-04-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_alter_switchport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchport',
            name='rx_signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchport',
            name='tx_signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchport',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SwitchVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField()),
                ('vlan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='snmp.switchport')),
            ],
        ),
    ]
