# Generated by Django 4.2.6 on 2024-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0003_alter_historicalswitch_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='high_signal_value',
            field=models.FloatField(blank=True, default='-11', null=True),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='high_signal_value',
            field=models.FloatField(blank=True, default='-11', null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
