# Generated by Django 4.2.6 on 2023-11-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0004_remove_olt_device_model_remove_olt_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olt',
            old_name='device_general_oid',
            new_name='sysDescr_oid',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='device_general_oid',
            new_name='sysDescr_oid',
        ),
    ]
