# Generated by Django 4.2.6 on 2023-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0004_alter_switch_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
