# Generated by Django 4.2.6 on 2023-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0004_remove_olt_model_remove_olt_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
