# Generated by Django 4.2.11 on 2025-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0004_switchport_rx_signal_switchport_tx_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='vlan_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
