# Generated by Django 4.2.6 on 2023-11-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0005_rename_device_general_oid_olt_sysdescr_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='uptime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='uptime',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
