# Generated by Django 4.2.6 on 2024-02-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0005_alter_historicalswitch_uplink_alter_switch_uplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='uplink',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.switch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.switch'),
        ),
    ]
