# Generated by Django 4.2.6 on 2023-10-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0005_olt_hostname_switch_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='hostname',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='sysinfo',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='uptime',
            field=models.DurationField(default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='sysinfo',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uptime',
            field=models.DurationField(default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
