# Generated by Django 4.2.6 on 2023-10-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0005_olt_hostname_switch_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='oid',
            field=models.CharField(default='1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4', max_length=300),
        ),
        migrations.AddField(
            model_name='switch',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='sysinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='uptime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='sysinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uptime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
