# Generated by Django 4.2.6 on 2023-10-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0006_alter_olt_hostname_alter_olt_sysinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='sysinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='uptime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='sysinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uptime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
