# Generated by Django 4.2.6 on 2024-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0006_alter_historicalswitch_uplink_alter_switch_uplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='snmp2netread', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='netman', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='snmp2netread', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='netman', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1),
        ),
    ]
