# Generated by Django 4.2.6 on 2023-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0007_alter_olt_hostname_alter_olt_sysinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
