# Generated by Django 4.2.6 on 2023-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0007_rename_sysdescr_oid_olt_sysdescr_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmodel',
            name='part_num_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='rx_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='sfp_vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='tx_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
