# Generated by Django 4.2.6 on 2023-11-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0008_switchmodel_part_num_oid_switchmodel_rx_oid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subnet',
        ),
    ]
