# Generated by Django 4.2.6 on 2024-02-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0009_rename_mac_historicalswitch_switch_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=1, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='switchesports',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
