# Generated by Django 4.2.6 on 2023-11-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0009_delete_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalswitch',
            name='device_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.switchmodel'),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.switchmodel'),
        ),
    ]
