# Generated by Django 4.2.6 on 2023-11-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0010_historicalswitch_device_model_switch_device_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalswitch',
            name='device_model_local',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_model_local',
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='uplink',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.switch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='uplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.switch'),
        ),
    ]
