# Generated by Django 4.2.6 on 2024-02-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0011_alter_historicalswitch_id_alter_switch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='ports',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='ports',
            new_name='port',
        ),
    ]
