# Generated by Django 4.2.6 on 2024-02-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0011_remove_historicalswitch_device_model_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subnet', models.GenericIPAddressField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_model_olt',
        ),
        migrations.RemoveField(
            model_name='historicalolt',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Olt',
        ),
        migrations.RemoveField(
            model_name='oltmodel',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='ats',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='device_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='device_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='historicalswitch',
            old_name='device_snmp_community',
            new_name='snmp_community',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='ats',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='device_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='device_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='device_snmp_community',
            new_name='snmp_community',
        ),
        migrations.RemoveField(
            model_name='historicalswitch',
            name='device_hostname',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_hostname',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='HistoricalOlt',
        ),
        migrations.DeleteModel(
            name='OltModel',
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.branch'),
        ),
        migrations.AddField(
            model_name='switch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.branch'),
        ),
    ]
