# Generated by Django 4.2.6 on 2024-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0012_branch_remove_device_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswitch',
            name='high_signal_value',
            field=models.FloatField(blank=True, default='11', null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='high_signal_value',
            field=models.FloatField(blank=True, default='11', null=True),
        ),
    ]
