# Generated by Django 4.2.6 on 2024-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0012_rename_ports_historicalswitch_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchesports',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
