# Generated by Django 4.2.6 on 2024-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0014_historicalswitch_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmodel',
            name='max_ports',
            field=models.IntegerField(default=28),
        ),
    ]
