# Generated by Django 4.2.6 on 2024-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0016_remove_switch_switches_status_82e56c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchesports',
            name='poe_admin',
        ),
        migrations.RemoveField(
            model_name='switchesports',
            name='poe_class',
        ),
        migrations.RemoveField(
            model_name='switchesports',
            name='poe_detection',
        ),
        migrations.RemoveField(
            model_name='switchesports',
            name='poe_mpower',
        ),
        migrations.RemoveField(
            model_name='switchesports',
            name='stp_admin',
        ),
        migrations.RemoveField(
            model_name='switchesports',
            name='stp_state',
        ),
        migrations.RemoveField(
            model_name='switchmodel',
            name='max_ports',
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='admin_state_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='description_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='duplex_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='max_ports_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='oper_state_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='port_num_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='speed_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
