# Generated by Django 4.2.6 on 2024-03-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0019_alter_ats_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ats',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.branch'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='ats',
        ),
    ]
