# Generated by Django 4.2.6 on 2024-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0020_alter_branch_unique_together_ats_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ats',
            name='subnet',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
