# Generated by Django 3.0.x on 2024-03-11 07:13
# NOTE: Fixed for Django 3.0 compatibility (CharField requires max_length).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0020_alter_branch_unique_together_ats_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ats',
            name='subnet',
            field=models.CharField(max_length=39, blank=True, null=True, unique=True),
        ),
    ]
