# Generated by Django 4.2.6 on 2024-03-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0021_alter_ats_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ats',
            name='subnet',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
