# Generated by Django 4.2.6 on 2024-03-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0022_alter_ats_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalswitch',
            name='ats',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.ats'),
        ),
        migrations.AddField(
            model_name='switch',
            name='ats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.ats'),
        ),
    ]
