# Generated by Django 4.2.6 on 2024-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0024_add_created_field_to_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalswitch',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
