# Generated by Django 3.0.14 on 2024-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0025_historicalswitch_created_alter_switch_created'),
    ]

    # NOTE:
    # This migration originally attempted to alter primary key fields.
    # On PostgreSQL deployments where PKs are implemented as IDENTITY columns,
    # altering them may fail (and it is not required for our app logic).
    # We keep this migration as a no-op (aside from model options) for safety.
    operations = [
        migrations.AlterModelOptions(
            name='historicalswitch',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical switch'},
        ),
    ]
