# Generated by Django 3.0.14 on 2025-07-25 07:32
# NOTE: This migration was made compatible with Django 3.0 (BigAutoField is not available).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0026_auto_20240704_1647'),
    ]

    # NOTE:
    # This migration originally attempted to alter primary key fields and history fields.
    # On some PostgreSQL deployments (IDENTITY PKs) such ALTERs may fail.
    # For current codebase these changes are not required, so we keep it minimal.
    operations = [
        migrations.AlterModelOptions(
            name='historicalswitch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical switch', 'verbose_name_plural': 'historical switchs'},
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='eriwpirt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='eriwpirt', max_length=20, null=True),
        ),
    ]
