# Generated by Django 5.0.6 on 2026-02-14 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0027_alter_historicalswitch_options_alter_ats_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_index', models.PositiveIntegerField()),
                ('if_name', models.CharField(blank=True, default='', max_length=128)),
                ('if_alias', models.CharField(blank=True, default='', max_length=255)),
                ('if_type', models.CharField(blank=True, default='', max_length=80)),
                ('is_optical', models.BooleanField(default=False)),
                ('admin_up', models.BooleanField(blank=True, null=True)),
                ('oper_up', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_interface',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetricBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_template', models.CharField(max_length=255)),
                ('index_strategy', models.CharField(choices=[('if_index', 'IfIndex'), ('fixed', 'Fixed'), ('vendor_map', 'Vendor Map')], default='if_index', max_length=20)),
                ('converter', models.CharField(choices=[('identity', 'Identity'), ('div100', 'Divide by 100'), ('div1000', 'Divide by 1000'), ('mw_to_dbm', 'mW to dBm'), ('enum_map', 'Enum map')], default='identity', max_length=20)),
                ('scale', models.FloatField(default=1.0)),
                ('enabled_by_default', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'metric_binding',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('text', 'Text'), ('enum', 'Enum')], default='float', max_length=10)),
                ('default_interval_sec', models.PositiveIntegerField(default=300)),
            ],
            options={
                'db_table': 'metric_definition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('quality', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('raw_value', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'metric_sample',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetricSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('warn_threshold', models.FloatField(blank=True, null=True)),
                ('crit_threshold', models.FloatField(blank=True, null=True)),
                ('poll_interval_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metric_subscription',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='public', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalswitch',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='private', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='public', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='private', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('vendor', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=160)),
                ('firmware', models.CharField(blank=True, default='', max_length=160)),
                ('sys_object_id', models.CharField(blank=True, default='', max_length=180)),
                ('snmp_version', models.CharField(choices=[('1', 'SNMPv1'), ('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='2c', max_length=4)),
                ('auth_profile', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('switch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='snmp.switch')),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=120)),
                ('model_pattern', models.CharField(max_length=255)),
                ('firmware_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'device_profile',
                'managed': True,
                'indexes': [models.Index(fields=['active', 'priority'], name='device_prof_active_474f68_idx'), models.Index(fields=['vendor'], name='device_prof_vendor_09c61b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceprofile',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_pattern', 'firmware_pattern'), name='uq_device_profile_vendor_model_fw'),
        ),
        migrations.AddField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp.deviceprofile'),
        ),
        migrations.AddField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='snmp.device'),
        ),
        migrations.AddField(
            model_name='metricbinding',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_bindings', to='snmp.deviceprofile'),
        ),
        migrations.AddIndex(
            model_name='metricdefinition',
            index=models.Index(fields=['key'], name='metric_defi_key_cb4c87_idx'),
        ),
        migrations.AddField(
            model_name='metricbinding',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='snmp.metricdefinition'),
        ),
        migrations.AddField(
            model_name='metricsubscription',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='snmp.metricbinding'),
        ),
        migrations.AddField(
            model_name='metricsubscription',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='snmp.device'),
        ),
        migrations.AddField(
            model_name='metricsubscription',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='snmp.interface'),
        ),
        migrations.AddField(
            model_name='metricsubscription',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='snmp.metricdefinition'),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='snmp.metricsubscription'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['vendor', 'model'], name='device_vendor_1d81bc_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'updated'], name='device_status_9caa29_idx'),
        ),
        migrations.AddIndex(
            model_name='interface',
            index=models.Index(fields=['device', 'is_optical'], name='device_inte_device__9292d0_idx'),
        ),
        migrations.AddIndex(
            model_name='interface',
            index=models.Index(fields=['device', 'if_index'], name='device_inte_device__aa7e6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('device', 'if_index'), name='uq_interface_device_ifindex'),
        ),
        migrations.AddIndex(
            model_name='metricbinding',
            index=models.Index(fields=['profile', 'enabled_by_default'], name='metric_bind_profile_dfd211_idx'),
        ),
        migrations.AddIndex(
            model_name='metricbinding',
            index=models.Index(fields=['metric', 'priority'], name='metric_bind_metric__ac6619_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricbinding',
            constraint=models.UniqueConstraint(fields=('profile', 'metric', 'oid_template', 'index_strategy'), name='uq_metric_binding_profile_metric_oid_index'),
        ),
        migrations.AddIndex(
            model_name='metricsubscription',
            index=models.Index(fields=['device', 'enabled'], name='metric_subs_device__d221db_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsubscription',
            index=models.Index(fields=['metric', 'enabled'], name='metric_subs_metric__7e7ef0_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', True)), fields=('device', 'metric'), name='uq_subscription_device_metric_no_interface'),
        ),
        migrations.AddConstraint(
            model_name='metricsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('interface', 'metric'), name='uq_subscription_interface_metric'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['subscription', 'ts'], name='metric_samp_subscri_76f5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['quality', 'ts'], name='metric_samp_quality_19e452_idx'),
        ),
    ]
