# Generated by Django 3.0.14 on 2026-01-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0027_alter_historicalswitch_options_alter_ats_id_and_more'),
    ]

    # NOTE:
    # Keep this migration focused on new MIB/capabilities fields only.
    # HistoricalSwitch AlterField operations are intentionally omitted to avoid
    # DB-specific issues (e.g. identity columns) and because they are not required
    # for monitoring functionality.
    operations = [
        migrations.AddField(
            model_name='switchesports',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='ddm_index_type',
            field=models.CharField(choices=[('ifIndex', 'ifIndex'), ('entPhysicalIndex', 'entPhysicalIndex')], default='entPhysicalIndex', help_text='Index type to use for DDM polling.', max_length=32),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='part_num_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='power_unit',
            field=models.CharField(choices=[('auto', 'auto'), ('dbm', 'dBm'), ('mw', 'mW'), ('scaled_dbm_100', 'scaled dBm/100'), ('scaled_mw_1000', 'scaled mW/1000 (uW)'), ('scaled_mw_10', 'scaled mW/10')], default='auto', max_length=32),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='required_mibs',
            field=models.CharField(blank=True, help_text="Comma-separated list of MIB modules to load (e.g. 'ENTITY-MIB,ENTITY-SENSOR-MIB')", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='rx_power_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='serial_num_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='sfp_vendor_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='temperature_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='temperature_unit',
            field=models.CharField(choices=[('auto', 'auto'), ('celsius', 'Celsius'), ('scaled_celsius_100', 'scaled Celsius/100')], default='auto', max_length=32),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='tx_power_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='voltage_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
