# Generated by Django 5.0.6 on 2026-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0028_interface_metricbinding_metricdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricbinding',
            name='binding_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
