# Generated by Django 3.0.14 on 2026-01-13 10:45

import re
from django.db import migrations


NUMERIC_OID_RE = re.compile(r'^\.?\d+(?:\.\d+)+$')


def _is_numeric_oid(value: str) -> bool:
    if not value:
        return False
    return bool(NUMERIC_OID_RE.match(value.strip()))


def seed_switchmodel_mib_config(apps, schema_editor):
    SwitchModel = apps.get_model('snmp', 'SwitchModel')

    # Seed a minimal configuration for a few common models using already existing
    # legacy OID fields as a fallback for MIB-based polling.
    #
    # NOTE: This does not guarantee full DOM/DDM coverage for every vendor;
    # it provides an out-of-the-box baseline so update_optical_info_mib can
    # query per-port values by ifIndex when numeric OIDs are available.
    target_models = [
        'MES3500-24',
        'DES-3200-18',
        'MA5603T',
    ]

    for model_name in target_models:
        try:
            sm = SwitchModel.objects.get(device_model=model_name)
        except SwitchModel.DoesNotExist:
            continue

        updates = {}

        # Load at least IF-MIB (used for interface table) even for numeric OIDs.
        updates['required_mibs'] = sm.required_mibs or 'IF-MIB'

        # Numeric OIDs from legacy config are indexed by ifIndex.
        updates['ddm_index_type'] = 'ifIndex'

        if _is_numeric_oid(sm.rx_oid) and not sm.rx_power_object:
            updates['rx_power_object'] = sm.rx_oid.strip()
        if _is_numeric_oid(sm.tx_oid) and not sm.tx_power_object:
            updates['tx_power_object'] = sm.tx_oid.strip()
        if _is_numeric_oid(sm.part_num_oid) and not sm.part_num_object:
            updates['part_num_object'] = sm.part_num_oid.strip()
        if _is_numeric_oid(sm.sfp_vendor) and not sm.sfp_vendor_object:
            updates['sfp_vendor_object'] = sm.sfp_vendor.strip()

        if updates:
            SwitchModel.objects.filter(pk=sm.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0028_switchmodel_mib_fields'),
    ]

    operations = [
        migrations.RunPython(seed_switchmodel_mib_config, migrations.RunPython.noop),
    ]
