# Generated by Django 3.0.14 on 2026-01-13 10:49

import re
from django.db import migrations


OID_RE = re.compile(r'^(?:iso\.)?\d+(?:\.\d+)+$')


def _normalize_numeric_oid(value: str):
    if not value:
        return None
    v = value.strip()
    if not OID_RE.match(v):
        return None
    if v.startswith('iso.'):
        v = '1' + v[len('iso'):]  # 'iso.3.6...' -> '1.3.6...'
    if v.startswith('.'):
        v = v[1:]
    return v


def normalize_legacy_oids_to_mib_objects(apps, schema_editor):
    SwitchModel = apps.get_model('snmp', 'SwitchModel')

    for sm in SwitchModel.objects.all().only('id', 'rx_oid', 'tx_oid', 'part_num_oid', 'sfp_vendor',
                                            'rx_power_object', 'tx_power_object', 'part_num_object', 'sfp_vendor_object'):
        updates = {}

        rx = _normalize_numeric_oid(getattr(sm, 'rx_oid', None))
        tx = _normalize_numeric_oid(getattr(sm, 'tx_oid', None))
        pn = _normalize_numeric_oid(getattr(sm, 'part_num_oid', None))
        sv = _normalize_numeric_oid(getattr(sm, 'sfp_vendor', None))

        if rx and not sm.rx_power_object:
            updates['rx_power_object'] = rx
        if tx and not sm.tx_power_object:
            updates['tx_power_object'] = tx
        if pn and not sm.part_num_object:
            updates['part_num_object'] = pn
        if sv and not sm.sfp_vendor_object:
            updates['sfp_vendor_object'] = sv

        # If we have any numeric legacy OIDs, they are indexed by ifIndex.
        if updates and getattr(sm, 'ddm_index_type', None) in (None, '', 'entPhysicalIndex'):
            updates.setdefault('ddm_index_type', 'ifIndex')

        if updates:
            SwitchModel.objects.filter(pk=sm.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0029_seed_switchmodel_mib_config'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_oids_to_mib_objects, migrations.RunPython.noop),
    ]
