# Generated by Django 5.0.6 on 2026-02-14 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0029_metricbinding_binding_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('direction', models.CharField(choices=[('lower_is_worse', 'Lower is worse'), ('higher_is_worse', 'Higher is worse')], default='lower_is_worse', max_length=20)),
                ('threshold', models.FloatField()),
                ('hysteresis', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='snmp.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='snmp.metricdefinition')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='snmp.deviceprofile')),
            ],
            options={
                'db_table': 'alert_rule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='snmp.metricsubscription')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='snmp.alertrule')),
            ],
            options={
                'db_table': 'alert_event',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['active', 'severity'], name='alert_rule_active_e28865_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric', 'active'], name='alert_rule_metric__372f52_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['state', 'severity'], name='alert_event_state_92704a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['subscription', 'state'], name='alert_event_subscri_30dcbc_idx'),
        ),
    ]
