# Generated by Django 3.0.14 on 2026-01-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0030_normalize_legacy_oids_to_mib_objects'),
    ]

    # NOTE:
    # Keep this migration focused on bandwidth-related models only.
    # Avoid altering PK fields (may fail on PostgreSQL IDENTITY columns).
    operations = [
        migrations.CreateModel(
            name='InterfaceBandwidthSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifindex', models.PositiveIntegerField()),
                ('ts', models.DateTimeField(db_index=True)),
                ('in_bps', models.BigIntegerField(blank=True, null=True)),
                ('out_bps', models.BigIntegerField(blank=True, null=True)),
                ('interval_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('in_octets', models.BigIntegerField(blank=True, null=True)),
                ('out_octets', models.BigIntegerField(blank=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snmp.Switch')),
            ],
            options={
                'db_table': 'interface_bandwidth_sample',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterfaceCounterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifindex', models.PositiveIntegerField()),
                ('last_in_octets', models.BigIntegerField(default=0)),
                ('last_out_octets', models.BigIntegerField(default=0)),
                ('last_ts', models.DateTimeField(blank=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snmp.Switch')),
            ],
            options={
                'db_table': 'interface_counter_state',
                'managed': True,
                'unique_together': {('switch', 'ifindex')},
            },
        ),
        migrations.AddIndex(
            model_name='interfacebandwidthsample',
            index=models.Index(fields=['switch', 'ifindex', 'ts'], name='interface_b_switch__7874bd_idx'),
        ),
    ]
