# Generated by Django 3.0.14 on 2026-01-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0031_bandwidth_samples'),
    ]

    # NOTE: Keep this migration focused on the new normalized schema tables only.
    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifindex', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('iftype', models.PositiveIntegerField(blank=True, null=True)),
                ('speed', models.BigIntegerField(blank=True, null=True)),
                ('duplex', models.SmallIntegerField(blank=True, null=True)),
                ('admin', models.SmallIntegerField(blank=True, null=True)),
                ('oper', models.SmallIntegerField(blank=True, null=True)),
                ('lastchange', models.BigIntegerField(blank=True, null=True)),
                ('discards_in', models.BigIntegerField(blank=True, null=True)),
                ('discards_out', models.BigIntegerField(blank=True, null=True)),
                ('polled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interfaces',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SwitchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=False)),
                ('uptime', models.CharField(blank=True, max_length=200, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('switch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='snmp.Switch')),
            ],
            options={
                'db_table': 'switch_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NeighborLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_mac', models.CharField(max_length=17)),
                ('remote_port', models.CharField(blank=True, max_length=64, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('local_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbor_links', to='snmp.Interface')),
                ('local_switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_links', to='snmp.Switch')),
            ],
            options={
                'db_table': 'neighbor_links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MacEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('vlan', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_entries', to='snmp.Interface')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_entries', to='snmp.Switch')),
            ],
            options={
                'db_table': 'mac_entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterfaceOptics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_dbm', models.FloatField(blank=True, null=True)),
                ('tx_dbm', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('sfp_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('polled_at', models.DateTimeField(blank=True, null=True)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optics', to='snmp.Interface')),
            ],
            options={
                'db_table': 'interface_optics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterfaceL2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pvid', models.PositiveIntegerField(blank=True, null=True)),
                ('tagged_vlans', models.CharField(blank=True, max_length=2000, null=True)),
                ('untagged_vlans', models.CharField(blank=True, max_length=200, null=True)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='l2', to='snmp.Interface')),
            ],
            options={
                'db_table': 'interface_l2',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='snmp.Switch'),
        ),
        migrations.AddIndex(
            model_name='neighborlink',
            index=models.Index(fields=['local_switch'], name='neighbor_li_local_s_193cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborlink',
            index=models.Index(fields=['remote_mac'], name='neighbor_li_remote__f0b977_idx'),
        ),
        migrations.AddIndex(
            model_name='macentry',
            index=models.Index(fields=['mac'], name='mac_entries_mac_755ace_idx'),
        ),
        migrations.AddIndex(
            model_name='macentry',
            index=models.Index(fields=['switch', 'interface'], name='mac_entries_switch__ff7c51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='macentry',
            unique_together={('switch', 'mac', 'vlan')},
        ),
        migrations.AddIndex(
            model_name='interface',
            index=models.Index(fields=['switch', 'ifindex'], name='interfaces_switch__10a63b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('switch', 'ifindex')},
        ),
    ]
