# Generated by Django 3.1.14 on 2026-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0032_merge_20260215_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricbinding',
            name='converter',
            field=models.CharField(choices=[('identity', 'Identity'), ('div10', 'Divide by 10'), ('div100', 'Divide by 100'), ('div1000', 'Divide by 1000'), ('mw_to_dbm', 'mW to dBm'), ('enum_map', 'Enum map')], default='identity', max_length=20),
        ),
    ]
