# Generated by Django 3.0.14 on 2026-01-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0032_normalize_schema_step1'),
    ]

    # NOTE: Keep this migration focused on adding the new normalized FK fields only.
    operations = [
        migrations.AddField(
            model_name='interfacebandwidthsample',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_samples', to='snmp.Interface'),
        ),
        migrations.AddField(
            model_name='interfacecounterstate',
            name='interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_state', to='snmp.Interface'),
        ),
        migrations.AddIndex(
            model_name='interfacebandwidthsample',
            index=models.Index(fields=['interface', 'ts'], name='interface_b_interfa_c932af_idx'),
        ),
    ]
