# Generated by Django 3.0.14 on 2026-01-13

from django.db import migrations


def forwards(apps, schema_editor):
    Switch = apps.get_model('snmp', 'Switch')
    SwitchesPorts = apps.get_model('snmp', 'SwitchesPorts')
    Interface = apps.get_model('snmp', 'Interface')
    InterfaceOptics = apps.get_model('snmp', 'InterfaceOptics')
    InterfaceL2 = apps.get_model('snmp', 'InterfaceL2')
    Mac = apps.get_model('snmp', 'Mac')
    MacEntry = apps.get_model('snmp', 'MacEntry')
    SwitchesNeighbors = apps.get_model('snmp', 'SwitchesNeighbors')
    NeighborLink = apps.get_model('snmp', 'NeighborLink')
    SwitchStatus = apps.get_model('snmp', 'SwitchStatus')
    InterfaceCounterState = apps.get_model('snmp', 'InterfaceCounterState')
    InterfaceBandwidthSample = apps.get_model('snmp', 'InterfaceBandwidthSample')

    # 1) Switch -> SwitchStatus
    for sw in Switch.objects.all().iterator():
        SwitchStatus.objects.get_or_create(
            switch_id=sw.id,
            defaults={
                'is_up': bool(getattr(sw, 'status', False)),
                'uptime': getattr(sw, 'uptime', None),
                'last_poll_at': getattr(sw, 'last_update', None),
            },
        )

    # Helper: map (switch_id, ifindex) -> interface_id
    iface_map = {}

    # 2) SwitchesPorts -> Interface (+ Optics + L2)
    for p in SwitchesPorts.objects.all().iterator():
        iface, _ = Interface.objects.get_or_create(
            switch_id=p.switch_id,
            ifindex=p.port,
            defaults={
                'name': p.name,
                'description': p.description,
                'alias': p.alias,
                'speed': p.speed,
                'duplex': p.duplex,
                'admin': p.admin,
                'oper': p.oper,
                'lastchange': p.lastchange,
                'discards_in': p.discards_in,
                'discards_out': p.discards_out,
                'polled_at': p.data,
            },
        )
        iface_map[(p.switch_id, p.port)] = iface.id

        # Optics
        if any([p.rx_signal is not None, p.tx_signal is not None, p.sfp_vendor, p.part_number, p.serial_number]):
            InterfaceOptics.objects.update_or_create(
                interface_id=iface.id,
                defaults={
                    'rx_dbm': p.rx_signal,
                    'tx_dbm': p.tx_signal,
                    'sfp_vendor': p.sfp_vendor,
                    'part_number': p.part_number,
                    'serial_number': p.serial_number,
                    'polled_at': p.data,
                },
            )

        # L2
        InterfaceL2.objects.update_or_create(
            interface_id=iface.id,
            defaults={
                'mac_count': p.mac_count,
                'pvid': p.pvid,
                'tagged_vlans': p.port_tagged,
                'untagged_vlans': p.port_untagged,
            },
        )

    # 3) Mac -> MacEntry (link by switch+port if possible)
    for m in Mac.objects.all().iterator():
        interface_id = None
        try:
            # legacy FK to SwitchesPorts exists
            legacy_port = getattr(m, 'port', None)
            if legacy_port is not None:
                interface_id = iface_map.get((m.switch_id, legacy_port.port))
        except Exception:
            interface_id = None

        MacEntry.objects.update_or_create(
            switch_id=m.switch_id,
            mac=m.mac,
            vlan=m.vlan,
            defaults={
                'interface_id': interface_id,
                'ip': m.ip,
            },
        )

    # 4) Neighbors -> NeighborLink (best-effort)
    # Map switch_mac -> switch_id
    mac_to_switch_id = {
        sw.switch_mac: sw.id
        for sw in Switch.objects.exclude(switch_mac__isnull=True).exclude(switch_mac='').only('id', 'switch_mac')
    }

    for n in SwitchesNeighbors.objects.all().iterator():
        local_switch_id = mac_to_switch_id.get(n.mac1)
        if not local_switch_id:
            continue
        local_interface_id = iface_map.get((local_switch_id, n.port1))

        NeighborLink.objects.create(
            local_switch_id=local_switch_id,
            local_interface_id=local_interface_id,
            remote_mac=n.mac2,
            remote_port=str(n.port2),
        )

    # 5) Backfill InterfaceCounterState.interface
    for st in InterfaceCounterState.objects.filter(interface__isnull=True).iterator():
        interface_id = iface_map.get((st.switch_id, st.ifindex))
        if interface_id:
            InterfaceCounterState.objects.filter(pk=st.pk).update(interface_id=interface_id)

    # 6) Backfill InterfaceBandwidthSample.interface
    for s in InterfaceBandwidthSample.objects.filter(interface__isnull=True).iterator():
        interface_id = iface_map.get((s.switch_id, s.ifindex))
        if interface_id:
            InterfaceBandwidthSample.objects.filter(pk=s.pk).update(interface_id=interface_id)


def backwards(apps, schema_editor):
    # Irreversible in practice
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0033_normalize_schema_step2'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
