# Generated by Django 3.0.14 on 2026-01-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0034_data_migrate_normalized_schema'),
    ]

    # NOTE: This migration performs schema cleanup after migrating to the normalized Interface schema.
    # Keep it minimal to avoid DB-specific issues.
    operations = [
        # Drop legacy index that referenced switch-level optics fields
        migrations.RemoveIndex(model_name='switch', name='switches_status_8f77cc_idx'),

        # Drop deprecated switch-level optics and wrong relations
        migrations.RemoveField(model_name='switch', name='branch'),
        migrations.RemoveField(model_name='switch', name='neighbor'),
        migrations.RemoveField(model_name='switch', name='port'),
        migrations.RemoveField(model_name='switch', name='rx_signal'),
        migrations.RemoveField(model_name='switch', name='tx_signal'),
        migrations.RemoveField(model_name='switch', name='sfp_vendor'),
        migrations.RemoveField(model_name='switch', name='part_number'),

        # Keep historical model aligned
        migrations.RemoveField(model_name='historicalswitch', name='branch'),
        migrations.RemoveField(model_name='historicalswitch', name='neighbor'),
        migrations.RemoveField(model_name='historicalswitch', name='port'),
        migrations.RemoveField(model_name='historicalswitch', name='rx_signal'),
        migrations.RemoveField(model_name='historicalswitch', name='tx_signal'),
        migrations.RemoveField(model_name='historicalswitch', name='sfp_vendor'),
        migrations.RemoveField(model_name='historicalswitch', name='part_number'),

        # Bandwidth/counters: remove legacy addressing and enforce normalized FK
        migrations.AlterUniqueTogether(name='interfacecounterstate', unique_together=set()),
        migrations.RemoveField(model_name='interfacecounterstate', name='switch'),
        migrations.RemoveField(model_name='interfacecounterstate', name='ifindex'),
        migrations.AlterField(
            model_name='interfacecounterstate',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_state', to='snmp.Interface'),
        ),

        migrations.RemoveIndex(model_name='interfacebandwidthsample', name='interface_b_switch__7874bd_idx'),
        migrations.RemoveField(model_name='interfacebandwidthsample', name='switch'),
        migrations.RemoveField(model_name='interfacebandwidthsample', name='ifindex'),
        migrations.AlterField(
            model_name='interfacebandwidthsample',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_samples', to='snmp.Interface'),
        ),
    ]
