# Generated by Django 3.0.14 on 2026-01-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0035_normalize_cleanup'),
    ]

    operations = [
        migrations.DeleteModel(name='SwitchesNeighbors'),
        migrations.DeleteModel(name='SwitchesPorts'),
        migrations.DeleteModel(name='Mac'),
        migrations.DeleteModel(name='ListMacHistory'),
    ]
