# Generated by Django 5.0.6 on 2026-02-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0035_data_migrate_switch_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='snmp.branch'),
        ),
    ]
