# Generated by Django 5.0.6 on 2026-02-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0036_add_branch_hierarchy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwitchModel',
            new_name='DeviceModel',
        ),
        migrations.RenameModel(
            old_name='SwitchesNeighbors',
            new_name='DeviceNeighbor',
        ),
        migrations.RenameModel(
            old_name='SwitchesPorts',
            new_name='DevicePort',
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='switch',
            name='ats',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='model',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='neighbor',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='port',
        ),
        migrations.AlterModelTable(
            name='devicemodel',
            table='device_type',
        ),
        migrations.AlterModelTable(
            name='deviceneighbor',
            table='device_neighbors',
        ),
        migrations.AlterModelTable(
            name='deviceport',
            table='device_ports',
        ),
        migrations.DeleteModel(
            name='HistoricalSwitch',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
