# Generated by Django 3.0.14 on 2026-01-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0036_drop_legacy_models'),
    ]

    # NOTE: keep this migration minimal (new host groups + links)
    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_groups', to='snmp.Branch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='snmp.HostGroup')),
            ],
            options={
                'db_table': 'host_groups',
                'managed': True,
                'unique_together': {('branch', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='switch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='snmp.HostGroup'),
        ),
        migrations.AddField(
            model_name='historicalswitch',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snmp.HostGroup'),
        ),
        migrations.AddIndex(
            model_name='hostgroup',
            index=models.Index(fields=['branch', 'parent', 'sort_order', 'name'], name='host_groups_branch__3e26a1_idx'),
        ),
    ]
