# Generated by Django 3.0.14 on 2026-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0037_host_groups_tree'),
    ]

    # NOTE: create index defensively (may already exist on some DBs)
    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS switches_status_673637_idx ON switches(status, hostname, ip);',
            reverse_sql='DROP INDEX IF EXISTS switches_status_673637_idx;',
        ),
    ]
