# Generated by Django - Rename Switch to Device
# This migration renames models at Python level without changing DB schema
# Using db_table and db_column to preserve existing database structure

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0038_host_groups_fix'),
    ]

    operations = [
        # Rename SwitchModel -> DeviceModel (keeps db_table='switch_model')
        migrations.RenameModel(
            old_name='SwitchModel',
            new_name='DeviceModel',
        ),
        # Rename Switch -> Device (keeps db_table='switches')
        migrations.RenameModel(
            old_name='Switch',
            new_name='Device',
        ),
        # Rename SwitchStatus -> DeviceStatus (keeps db_table='switch_status')
        migrations.RenameModel(
            old_name='SwitchStatus',
            new_name='DeviceStatus',
        ),
        # Rename field switch_mac -> device_mac in Device
        migrations.RenameField(
            model_name='device',
            old_name='switch_mac',
            new_name='device_mac',
        ),
    ]
