# Generated by Django 4.2.28 on 2026-02-21 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0038_auto_20260215_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsubscription',
            name='poll_interval_sec',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'status', 'updated'], name='device_branch__4a0acb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['profile', 'status'], name='device_profile_b49c32_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['ts', 'id'], name='metric_samp_ts_a388ae_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['subscription', 'quality', 'ts'], name='metric_samp_subscri_76663b_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsubscription',
            index=models.Index(fields=['device', 'interface', 'enabled'], name='metric_subs_device__a1d426_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('poll_interval_sec__isnull', True), ('poll_interval_sec__gte', 5), _connector='OR'), name='chk_subscription_poll_interval_gte_5'),
        ),
    ]
