# Generated by Django 4.2.11 on 2026-01-14 11:32
# Add OpticsHistorySample and OpticsAlert models for historical data and alerting

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0039_rename_switch_to_device'),
    ]

    operations = [
        # OpticsHistorySample - for storing historical optical signal data
        migrations.CreateModel(
            name='OpticsHistorySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('rx_dbm', models.FloatField(blank=True, null=True)),
                ('tx_dbm', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optics_history', to='snmp.interface')),
            ],
            options={
                'db_table': 'optics_history_sample',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='opticshistorysample',
            index=models.Index(fields=['interface', 'ts'], name='optics_hist_interfa_idx'),
        ),
        migrations.AddIndex(
            model_name='opticshistorysample',
            index=models.Index(fields=['ts'], name='optics_hist_ts_idx'),
        ),
        
        # OpticsAlert - for tracking signal threshold violations
        migrations.CreateModel(
            name='OpticsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('rx_dbm', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optics_alerts', to='snmp.interface')),
            ],
            options={
                'db_table': 'optics_alerts',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='opticsalert',
            index=models.Index(fields=['status', 'severity'], name='optics_aler_status_idx'),
        ),
        migrations.AddIndex(
            model_name='opticsalert',
            index=models.Index(fields=['interface', 'status'], name='optics_aler_iface_idx'),
        ),
        migrations.AddIndex(
            model_name='opticsalert',
            index=models.Index(fields=['created_at'], name='optics_aler_created_idx'),
        ),
    ]
