# Generated by Django 4.2.28 on 2026-02-21 23:30

from django.db import migrations, models
from django.db.models.functions import Coalesce, Lower, Trim


def _normalize_name(raw_name):
    if raw_name is None:
        return None
    normalized = str(raw_name).strip()
    return normalized or None


def _dedupe_names(apps, schema_editor):
    Branch = apps.get_model('snmp', 'Branch')
    Ats = apps.get_model('snmp', 'Ats')

    # Normalize existing names first to align with the new uniqueness rules.
    for model in (Branch, Ats):
        for row in model.objects.all().values('id', 'name').iterator():
            normalized = _normalize_name(row['name'])
            if row['name'] != normalized:
                model.objects.filter(pk=row['id']).update(name=normalized)

    def dedupe_model(model, scope_field):
        seen = set()
        rows = model.objects.all().values('id', 'name', scope_field).order_by('id')
        for row in rows.iterator():
            name = row['name']
            if name is None:
                continue
            scope_id = row[scope_field]
            key = (scope_id, name.lower())
            if key not in seen:
                seen.add(key)
                continue

            base_name = name
            suffix_idx = 0
            while True:
                suffix_idx += 1
                suffix = f"{row['id']}" if suffix_idx == 1 else f"{row['id']}-{suffix_idx}"
                candidate = f"{base_name} ({suffix})"
                candidate_key = (scope_id, candidate.lower())
                if candidate_key not in seen:
                    model.objects.filter(pk=row['id']).update(name=candidate)
                    seen.add(candidate_key)
                    break

    dedupe_model(Branch, 'parent_id')
    dedupe_model(Ats, 'branch_id')


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0039_alter_alertevent_id_alter_alertrule_id_alter_ats_id_and_more'),
    ]

    operations = [
        migrations.RunPython(_dedupe_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(
                Lower(Trim('name')),
                Coalesce('parent_id', models.Value(0)),
                condition=models.Q(name__isnull=False),
                name='uq_branch_parent_norm_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='ats',
            constraint=models.UniqueConstraint(
                Lower(Trim('name')),
                Coalesce('branch_id', models.Value(0)),
                condition=models.Q(name__isnull=False),
                name='uq_ats_branch_norm_name',
            ),
        ),
    ]
