# Generated by Django 4.2.28 on 2026-02-22 00:00

from django.db import migrations, models
from django.db.models.functions import Coalesce, Lower, Trim


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0040_group_subgroup_normalized_uniqueness'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='device_branch__4a0acb_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ats',
            name='uq_ats_branch_norm_name',
        ),
        migrations.RenameField(
            model_name='ats',
            old_name='branch',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='branch',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ats',
            new_name='subgroup',
        ),
        migrations.RenameField(
            model_name='historicaldevice',
            old_name='branch',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='historicaldevice',
            old_name='ats',
            new_name='subgroup',
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['group', 'status', 'updated'], name='device_group_i_e4fc71_idx'),
        ),
        migrations.AddConstraint(
            model_name='ats',
            constraint=models.UniqueConstraint(
                Lower(Trim('name')),
                Coalesce('group_id', models.Value(0)),
                condition=models.Q(name__isnull=False),
                name='uq_ats_group_norm_name',
            ),
        ),
    ]
