# Generated by Django 4.2.28 on 2026-02-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0042_alter_ats_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='admin_state_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='description_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='duplex_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='max_ports_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='oper_state_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='part_num_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='port_num_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='rx_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='speed_oid',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='tx_oid',
        ),
        migrations.RemoveField(
            model_name='deviceport',
            name='mac_on_port',
        ),
    ]
