# Generated by Django 4.2.28 on 2026-02-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0043_remove_devicemodel_admin_state_oid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListMacHistory',
        ),
    ]
