# Generated by Django 4.2.28 on 2026-02-22 16:31

from django.db import migrations, models
import django.db.models.deletion


def backfill_metricsample_device(apps, schema_editor):
    MetricSample = apps.get_model('snmp', 'MetricSample')
    pending = (
        MetricSample.objects
        .filter(device__isnull=True, subscription__device__isnull=False)
        .select_related('subscription')
        .only('id', 'device_id', 'subscription_id', 'subscription__device_id')
    )
    to_update = []
    for sample in pending.iterator(chunk_size=2000):
        sample.device_id = sample.subscription.device_id
        to_update.append(sample)
        if len(to_update) >= 2000:
            MetricSample.objects.bulk_update(to_update, ['device'])
            to_update = []
    if to_update:
        MetricSample.objects.bulk_update(to_update, ['device'])


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0044_delete_listmachistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='neighbor',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='parent_port',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='metricsample',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='snmp.device'),
        ),
        migrations.RunPython(backfill_metricsample_device, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['device', 'ts'], name='metric_samp_device__53ba4f_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalDevice',
        ),
    ]
