# Generated by Django 4.2.28 on 2026-02-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0045_remove_historicaldevice_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsample',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='snmp.device'),
        ),
    ]
